version: '3.5'

services:
  opensearch:
    image: opensearchproject/opensearch:2.6.0
    environment:
      discovery.type: "single-node"
      plugins.security.disabled: true
      OPENSEARCH_JAVA_OPTS: "-Xms4g -Xmx25g"
    ports:
      - "9201:9200"
      - "9301:9300"
    logging:
      driver: "json-file"
      options:
        max-file: 1
        max-size: 10m
    deploy:
      resources:
        limits:
          memory: 25Gb
