version: '3.7'

services:
  qdrant_bench:
    image: qdrant/qdrant:v1.1.0
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - ./storage:/qdrant/storage
    environment:
      - QDRANT__STORAGE__HNSW_INDEX__MAX_INDEXING_THREADS=8
      - QDRANT__STORAGE__PERFORMANCE__MAX_OPTIMIZATION_THREADS=8
      - QDRANT__SERVICE__MAX_WORKERS=16
    logging:
      driver: "json-file"
      options:
        max-file: 1
        max-size: 10m
    deploy:
      resources:
        limits:
          memory: 400Gb
